package model;

public enum MetroEventsEnum {
    OPEN_METROSTATION,BUY_METROCARD,BUY_METROCARDTICKETS,SCAN_METROCARDS,Alert_CONTROLCENTER, WALKTHROUGHGATE,ACTIVATE_GATE,DEACTIVATE_GATE,UPDATE_METROCARD,SCAN_METROCARDS_SUCCESFULL,CLOSE_METROSTATION;
}
